version: "3.8"

services:
  downstream:
    image: nginx:alpine
    ports:
      - 8282:80
    networks: 
      - keycloak-network

  echo:
    image: gcr.io/google_containers/echoserver:1.8
#    ports:
#      - 8383:8080
    networks: 
      - keycloak-network

  proxy:
    build: .
    ports:
      - 80:80
    volumes:
      - ./bootstrap.sh:/usr/local/openresty/bootstrap.sh
    environment:
      - OID_SESSION_SECRET=623q4hR325t36VsCD3g567922IC0073T
      - OID_SESSION_CHECK_SSI=off
      - OID_SESSION_NAME=oidc_auth

      - OID_REDIRECT_PATH=/redirect_uri
      - OID_DISCOVERY=http://DOCKERHOST:8080/auth/realms/neobox/.well-known/openid-configuration
      - OID_CLIENT_ID=proxy
      - OID_CLIENT_SECRET=dee59d02-b1a9-455a-bd3c-38d2e060bf0f

      - PROXY_HOST=echo
      - PROXY_PORT=8080
      - PROXY_PROTOCOL=http
    networks: 
      - keycloak-network

#  keycloak:
#    image: jboss/keycloak
#    ports:
#      - 8080:8080
#    environment:
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
#    networks: 
#      - keycloak-network

networks:
  keycloak-network:
    external:
      name: keycloak-network

